GET http://localhost:3000/items HTTP/1.1
content-type: application/json

###

POST http://localhost:3000/items HTTP/1.1
content-type: application/json

{
  "item": "xis'); DROP TABLE IF EXISTS items; CREATE TABLE student (INTEGER PRIMARY KEY,first_name TEXT,last_name TEXT,age INTEGER,student_email TEXT NOT NULL,class TEXT"
}

###

PUT http://localhost:3000/items/5 HTTP/1.1
Content-Type: application/json

{
    "item": "udated item"
}

###

DELETE http://localhost:3000/items/1 HTTP/1.1
Content-Type: application/json