GET http://localhost:3000/items HTTP/1.1
content-type: application/json

###

POST http://localhost:3000/items HTTP/1.1
content-type: application/json

{
    "item": "new item"
}

###

PUT http://localhost:3000/items/a9ef3def-a60c-4525-af6b-f57365b29d06 HTTP/1.1
Content-Type: application/json

{
    "item": "updated item"
}

###

DELETE http://localhost:3000/items/845f7609-cd3e-4176-8be2-3f9fcfe55877 HTTP/1.1
Content-Type: application/json