GET http://localhost:3000/items HTTP/1.1
content-type: application/json

###

POST http://localhost:3000/items HTTP/1.1
content-type: application/json

{
    "item": "new item"
}

###

PUT http://localhost:3000/items/c9ca8984-7d41-424e-949b-0a559d08c8b6 HTTP/1.1
Content-Type: application/json

{
    "item": "updated item"
}

###

DELETE http://localhost:3000/items/8a18bf4b-7788-41b7-920f-abc5555b638f HTTP/1.1
Content-Type: application/json